### ISSUE TITLE
Node 20.10.0 : error @achrinza/node-ipc@9.2.5: The engine "node" is incompatible with this module.

### ISSUE THREAD

**Issue by rajinder-yadav** [achrinza/node-ipc#59] opened 2024-01-22 14:26 UTC
Can we get this working for Node 20.10.0

See this error trying to install latest release of Angular.

```sh
error @achrinza/node-ipc@9.2.5: The engine "node" is incompatible with this module. Expected version "8 || 9 || 10 || 11 || 12 || 13 || 14 || 15 || 16 || 17 || 18". Got "20.10.0"
error Found incompatible module.
```

**Comment by achrinza** [comment] 2024-02-26 14:34
Thanks for raising this and apologies for the delayed response.

Will timebox some time this week to resolve this.

**Comment by achrinza** [comment] 2024-02-26 14:40
Duplicate of https://github.com/achrinza/node-ipc/issues/45
Closed by https://github.com/achrinza/node-ipc/issues/45

**Closed as completed by achrinza** 2024-02-26 14:40 UTC
